services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_net

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      N8N_PORT: 8443
      TZ: ${TZ:-Europe/Amsterdam}
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: ${DB_POSTGRESDB_HOST}
      DB_POSTGRESDB_PORT: ${DB_POSTGRESDB_PORT}
      DB_POSTGRESDB_DATABASE: ${DB_POSTGRESDB_DATABASE}
      DB_POSTGRESDB_USER: ${DB_POSTGRESDB_USER}
      DB_POSTGRESDB_PASSWORD: ${DB_POSTGRESDB_PASSWORD}
      N8N_RUNNERS_ENABLED: "true"
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER:-admin}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD:-change_me}
      API_BASE_URL: ${API_BASE_URL}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "false"
      N8N_GIT_NODE_DISABLE_BARE_REPOS: "true"
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_PROTOCOL: "https"
      WEBHOOK_URL: ${WEBHOOK_URL}
      N8N_COMMUNITY_PACKAGES_ENABLED: "false"
      N8N_HOST: ${N8N_HOST}
      N8N_EDITOR_BASE_URL: ${N8N_EDITOR_BASE_URL}
      YANDEX_GPT_KEY: ${YANDEX_GPT_KEY}
      YANDEX_GPT_CATALOG: ${YANDEX_GPT_CATALOG}
      # Custom variables
      BACKEND_URL: ${BACKEND_URL}
    ports:
      - "8443:8443"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - app_net

volumes:
  pgdata:
  n8n_data:

networks:
  app_net:
    driver: bridge